version: "3.9"

services:
  db:
    network_mode: "host"
    container_name: lenslocked
    image: postgres
    restart: always
    platform: linux/amd64
    environment:
      - POSTGRES_DB=lenslocked
      - POSTGRES_USER=lenslocked
      - POSTGRES_PASSWORD=lenslocked
      - PG_TRUST_LOCALNET=true
    volumes:
      - ./testdata/dockervolume/pgdata:/var/lib/postgresql/data

  pgadmin:
    network_mode: "host"
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pg.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - ./testdata/dockervolume/pgadmindata:/var/lib/pgadmin
      # run: $ sudo chown -R 5050:5050 ./testdata/dockervolume/pgadmindata
    depends_on:
      - db
