version: "3.9"

services:
  db:
    container_name: dblenslocked
    image: postgres
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_DB: lenslocked
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lenslocked-secret
    volumes:
      - ./testdata/dockervolume/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
