version: '3'

tasks:
  build:
    aliases:
      - b
    cmds:
      - go build -o ./bin/lenslocked main.go

  clean:
    aliases:
      - c
    cmds:
      - rm bin

  clean-build:
    aliases:
      - cb
    cmds:
      - task: c
      - task: b

  run:
    aliases:
      - r
    cmds:
      - task: b
      - air -d -c .air.dev.toml

  test:
    aliases:
      - t
    cmds:
      - go test -v ./... -timeout 15s