CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    birth DATE NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);